# traefik/dynamic/routers.yml

http:
  routers:
    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      service: noop-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    https-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      service: noop-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - ruture auth solution

    traefik-dashboard:
      rule: "Host(`traefik.joe-taylor.me`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - ruture auth solution

    noop-router:
      rule: "Host(`noop.joe-taylor.me`)"
      service: noop-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - future auth solution

    changedetection-router:
      rule: "Host(`changedetection.joe-taylor.me`)"
      service: changedetection-dynamic
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - future auth solution