# traefik/dynamic/routers.yml

http:
  routers:
    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      service: noop-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    https-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      service: noop-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - ruture auth solution

    traefik-dashboard:
      rule: "Host(`traefik.joe-taylor.me`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - ruture auth solution

    noop-router:
      rule: "Host(`noop.joe-taylor.me`)"
      service: noop-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - future auth solution

    changedetection-router:
      rule: "Host(`changedetection.joe-taylor.me`)"
      service: changedetection-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      # middlewares:
      #   - future auth solution

    supabase-studio-router:
      rule: "Host(`studio.supabase.joe-taylor.me`)"
      service: supabase-studio-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    supabase-kong-router:
      rule: "Host(`supabase.joe-taylor.me`)"
      service: supabase-kong-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    supagate-router:
      rule: "Host(`supagate.joe-taylor.me`)"
      service: supagate-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare